Part 1:

In [ ]:
import numpy as np

Question 1:

In [ ]:
arr = np.zeros(10, dtype = int)
print("Array of 10 zeroes: ")
print(arr)

arr = np.ones(10, dtype= int)
print("Array of 10 ones: ")
print(arr)

arr = arr * 5 # matrix multiplication operation
print("Array of 10 fives: ")
print(arr)

Array of 10 zeroes: 
[0 0 0 0 0 0 0 0 0 0]
Array of 10 ones: 
[1 1 1 1 1 1 1 1 1 1]
Array of 10 fives: 
[5 5 5 5 5 5 5 5 5 5]


question 2:

In [ ]:
arr = np.arange(10, 51, 2, dtype = int)
print("An array of even numbers from 10 to 50: \n")
print(arr)

An array of even numbers from 10 to 50: 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


question 3:

In [ ]:
rand_val = np.random.rand()
print("Randomly* generated value between 0 and 1: \n")
print(rand_val)

# generating a 3 * 5 matrix of random value between 0 and 1
rand_arr = np.random.rand(3,3)
print("\na matrix consisting of random values between 0 and 1: \n")
print(rand_arr)

Randomly* generated value between 0 and 1: 

0.022916974234777343

a matrix consisting of random values between 0 and 1: 

[[0.14592428 0.9724816  0.20715234]
 [0.24842958 0.91983072 0.14688253]
 [0.24956248 0.23327253 0.19178245]]


question 4:

In [ ]:
np.savetxt('matrix.txt', rand_arr, delimiter=',')
f = open("matrix.txt", "r")
print("Matrix stored in the text file is: \n")
print(f.read())

Matrix stored in the text file is: 

1.459242830197350349e-01,9.724815994443970490e-01,2.071523356399611604e-01
2.484295823888840182e-01,9.198307162464584019e-01,1.468825257732720990e-01
2.495624768487589851e-01,2.332725287258595737e-01,1.917824475382218230e-01



Part 2:

question 1:

In [ ]:
import pandas as pd
import numpy as np
from PIL import Image
f = Image.open("image.jpg") ## extract the pixel data from the image using PIL (python image library)
pixel = np.asarray(f) ## convert the pixel data generated using PIL into a numpy 3D array

# for storing the data in excel sheet using pandas, we will use pandas dataframe but DataFrame function takes 2D array as a argument
# have to convert 3D pixel data array to 2D array
# since PIL returns a 3D list with each pixel reperesented by a list of size 3, containing RGB values.
# list of RGB values of pixels of each line are put in a single list.
# list of each line are elements of a list.

#idea to convert the 3D list to a pandas dataframe, but pd.DataFrame(list) accepts only 2D list as arguments.
# so we do some data wrangling by creating a 2D list of size [3][number of pixel list in the 3D original list]
# first row will contain the first value of each pixel list, second row contains the second value of pixel list and third row contains the third value of pixel list
# The original 3D image data list can be recreated from the data frame if needed with some processing.
temp = np.zeros([3, len(pixel) * len(pixel[0])], dtype= int)
ct = 0
for i in pixel:
  for j in i:
    temp[0][ct] = j[0]
    temp[1][ct] = j[1]
    temp[2][ct] = j[2]
    ct += 1

df = pd.DataFrame(temp)
df.to_csv('image.csv', index= False) # put index = false in the parameter to store the Dataframe without the index

# first row and first column represent the column and row index respectively in the above .csv file

question 2:

In [ ]:
import pandas as pd
# import the data from csv file and store it in a pandas DataFrame
col = []
for i in range(0,(len(pixel) * len(pixel[0])) - 1): #creating a list of column numbers from 0 to second last column number(ignoring last column)
  col.append(i)

df = pd.read_csv('image.csv', skiprows=[2], usecols= col) ## skiprows = [2] to ignore the last row (row with index 2) and col is the list of indexes of columns which are to be used
# df is the DataFrame of the matrix stored in .csv file with last row and last column ignored
print(df)




    0   1   2   3   4   5  ...  921593  921594  921595  921596  921597  921598
0  21  21  21  21  21  21  ...      23      23      23      23      23      23
1  91  91  91  91  91  91  ...      56      56      56      56      56      56

[2 rows x 921599 columns]


question 3:

In [ ]:
import pandas as pd
date = pd.datetime.now().date()

print("today's date is: " + str(date))

today's date is: 2020-08-23


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime instead.
  


part 3:

question 1:

In [ ]:
from datetime import date
import math as mt
print("-------------------- Mini age calculator -------------------------")

print("Enter your year of birth: \n")
year = input()
print("Enter your month of birth (in number): \n")
month = input()
print("Enter your day of birth (in number): \n")
day = input()

birthday = date(int(year), int(month), int(day))

today = date.today()

days_in_a_year = 365.2425  # number of days in a year (the extra partial day accumulates to form one extra day in a leap year)
age = (today - birthday).days / days_in_a_year

print("Your age is: " + str(mt.floor(age)) + " years")

-------------------- Mini age calculator -------------------------
Enter your year of birth: 

2001
Enter your month of birth (in number): 

8
Enter your day of birth (in number): 

22
Your age is: 19 years
